import {PromoCode,PromoUsage,PromoUserCounter,Transaction} from '../models/index.js';
import {ledger,withMongoTransaction} from './ledger.js';

async function qualifyingVolume(userId:string){const rows=await Transaction.aggregate([{$match:{userId,type:'DEPOSIT',status:'COMPLETED'}},{$group:{_id:null,total:{$sum:'$amount'}}}]);return Number(rows[0]?.total||0)}
export async function validatePromo(code:string,userId:string){const p=await PromoCode.findOne({code:code.trim().toUpperCase(),status:'ACTIVE'});if(!p)throw Error('Invalid promo code');const now=new Date();if(p.expiresAt&&p.expiresAt<=now)throw Error('Promo code expired');if(p.minRequirement&&await qualifyingVolume(userId)<Number(p.minRequirement))throw Error(`Minimum requirement is ${p.minRequirement}`);const used=await PromoUserCounter.findOne({promoCodeId:p._id,userId});if(p.perUserLimit&&Number(used?.count||0)>=p.perUserLimit)throw Error('Per-user usage limit reached');if(p.usageLimit&&Number(p.usageCount||0)>=p.usageLimit)throw Error('Usage limit reached');return p}
export async function applyPromo(code:string,userId:string,usageKey?:string){
 const normalized=code.trim().toUpperCase();const initial=await validatePromo(normalized,userId);const key=usageKey?.trim()||`PROMO-${initial._id}-${userId}-${Date.now()}-${Math.random().toString(36).slice(2)}`;const reference=`PROMO-${initial.code}-${userId}-${key}`;
 const work=async(session:any)=>{const prior=await Transaction.findOne({userId,type:'PROMO_REWARD',reference,status:'COMPLETED'}).session(session);if(prior)return prior;const p=await PromoCode.findOne({_id:initial._id,status:'ACTIVE',$or:[{expiresAt:null},{expiresAt:{$gt:new Date()}}]}).session(session);if(!p)throw Error('Promo code is no longer active');if(p.minRequirement&&await qualifyingVolume(userId)<Number(p.minRequirement))throw Error(`Minimum requirement is ${p.minRequirement}`);if(p.usageLimit){const updated=await PromoCode.findOneAndUpdate({_id:p._id,status:'ACTIVE',usageCount:{$lt:p.usageLimit}},{$inc:{usageCount:1}},{new:true,session});if(!updated)throw Error('Usage limit reached')}else await PromoCode.updateOne({_id:p._id},{$inc:{usageCount:1}},{session});const counter=await PromoUserCounter.findOneAndUpdate({promoCodeId:p._id,userId,...(p.perUserLimit?{count:{$lt:p.perUserLimit}}:{})},{$inc:{count:1},$setOnInsert:{promoCodeId:p._id,userId}},{upsert:true,new:true,session});if(!counter)throw Error('Per-user usage limit reached');let usage;try{usage=(await PromoUsage.create([{promoCodeId:p._id,userId,reward:p.rewardValue,usageKey:key}],{session}))[0]}catch(e:unknown){if((e as {code?:number})?.code===11000){const existing=await Transaction.findOne({userId,type:'PROMO_REWARD',reference,status:'COMPLETED'}).session(session);if(existing)return existing}throw e}return ledger({userId,type:'PROMO_REWARD',amount:Number(p.rewardValue),status:'COMPLETED',reference,metadata:{promoId:String(p._id),usageId:String(usage._id),idempotencyKey:key}},session)};
 return withMongoTransaction(work);
}
