import mongoose,{ClientSession} from 'mongoose';
import {User,Commission} from '../models/index.js';
import {ledger,withMongoTransaction} from './ledger.js';
import {getSettings} from './settingsService.js';

export async function getUpline(userId:string,max=4,session?:ClientSession){const result:{level:number;userId:unknown;name:string;memberId:string;status:string}[]=[];const seen=new Set([userId]);let current=await User.findById(userId).select('referredBy').session(session||null);for(let level=1;level<=Math.min(4,max)&&current?.referredBy;level++){const id=String(current.referredBy);if(seen.has(id))break;seen.add(id);const parent=await User.findById(id).select('_id referredBy fullName userId status').session(session||null);if(!parent)break;result.push({level,userId:parent._id,name:parent.fullName,memberId:parent.userId,status:parent.status});current=parent}return result}

async function createCommissionsInSession(sourceUserId:string,baseAmount:number,sourceReference:string,session:ClientSession){const settings=await getSettings();const rates=(settings.commissionRates||[10,2,1,1]).slice(0,4).map(Number);const chain=await getUpline(sourceUserId,4,session);const created=[];for(const u of chain){const rate=Number(rates[u.level-1]||0);if(rate<=0)continue;const amount=Number((baseAmount*rate/100).toFixed(8));if(amount<=0)continue;const exists=await Commission.findOne({sourceUserId,level:u.level,transactionId:sourceReference}).session(session);if(exists)continue;let c;try{c=(await Commission.create([{userId:new mongoose.Types.ObjectId(String(u.userId)),sourceUserId,level:u.level,rate,amount,transactionId:sourceReference}],{session}))[0]}catch(e:unknown){if((e as {code?:number})?.code===11000)continue;throw e}await ledger({userId:String(u.userId),type:'COMMISSION',amount,status:'COMPLETED',reference:`COM-${sourceReference}-L${u.level}`,metadata:{commissionId:String(c._id),sourceReference,level:u.level,idempotencyKey:`commission:${sourceReference}:${u.level}`}},session);created.push(c)}return created}

export async function createCommissions(sourceUserId:string,baseAmount:number,sourceReference:string,session?:ClientSession){if(session)return createCommissionsInSession(sourceUserId,baseAmount,sourceReference,session);return withMongoTransaction(s=>createCommissionsInSession(sourceUserId,baseAmount,sourceReference,s));}
